apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: chaosguard
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: chaosguard
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream auth-service {
            server auth-service:8081;
        }
        
        upstream product-service {
            server product-service:8082;
        }
        
        upstream payment-service {
            server payment-service:8083;
        }
        
        server {
            listen 80;
            
            location /auth/ {
                proxy_pass http://auth-service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            location /products/ {
                proxy_pass http://product-service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            location /payment/ {
                proxy_pass http://payment-service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            location /health {
                return 200 'Gateway healthy';
                add_header Content-Type text/plain;
            }
        }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: chaosguard
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort