apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: chaosguard
  labels:
    app: payment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: payment-service
        image: chaosguard/payment-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          value: "8083"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: chaosguard
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 8083
    targetPort: 8083
    name: http
  type: ClusterIP